apiVersion: v1
kind: Namespace
metadata:
  name: otusapp
  labels:
    name: "dsamoshkin"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dsamoshkin"
  namespace: otusapp
spec:
  selector:
    matchLabels:
      app: "dsamoshkin"
  replicas: 3
  template:
    metadata:
      labels:
        app: "dsamoshkin"
    spec:
      containers:
        - name: "dsamoshkin"
          image: "aroks/k8graalapp:1.0.0"
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "dsamoshkin"
  namespace: otusapp
spec:
  selector:
    app: "dsamoshkin"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dsamoshkin
  namespace: otusapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/dsamoshkin(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: dsamoshkin
              servicePort: 8000